# Generated by Django 3.2.9 on 2021-11-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': 'Goods'},
        ),
        migrations.AlterModelOptions(
            name='goods_images',
            options={'verbose_name_plural': 'goods_images'},
        ),
        migrations.AddField(
            model_name='goods',
            name='price_r',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=51),
            preserve_default=False,
        ),
    ]
