# Generated by Django 3.2.9 on 2021-11-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegraminfo',
            name='chat_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
