# Generated by Django 3.2.9 on 2021-11-12 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0002_alter_telegraminfo_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegraminfo',
            name='chat_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='telegraminfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
